version: "3.0"

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200


  #db:
  #  image: postgres:latest
   # environment:
    #  - "POSTGRES_HOST_AUTH_METHOD=trust"
   # container_name: db
   # ports:
    #  - 5432:5432


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

 # restapi:
  #  image: petebids/blog
   # depends_on:
    #  - db
     # - elasticsearch
     # - rabbitmq
   # container_name: rest-api
   # ports:
   #   - 8080:8080

